version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: suchashop_mongodb
    ports:
      - "27017:27017"
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval \"try { rs.status().ok } catch (e) { rs.initiate({ _id: 'rs0', members: [{ _id: 0, host: 'localhost:27017' }] }); }\""]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mongodb_data: